import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/widgets/NavBar/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import MobileNavBar from "@/components/widgets/NavBar/MobileNavBar";
import Footer from "@/components/widgets/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          // enableSystem
          // disableTransitionOnChange
        >
          {/* nav for larg screen  */}
          <NavBar />
          {/* nav for small screen */}
          <MobileNavBar/>

          {children}
          {/* footer  */}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
